# Generated by Django 4.1.4 on 2023-01-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='goal',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.IntegerField(choices=[(0, 'doing'), (1, 'Done'), (2, 'Wasted')]),
        ),
        migrations.AlterField(
            model_name='work',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='work',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.IntegerField(choices=[(0, 'doing'), (1, 'Done'), (2, 'Wasted')]),
        ),
        migrations.AddField(
            model_name='goal',
            name='purpose',
            field=models.ManyToManyField(blank=True, to='todolist.goal'),
        ),
        migrations.AddField(
            model_name='work',
            name='purpose',
            field=models.ManyToManyField(blank=True, related_name='work_goals', to='todolist.goal'),
        ),
    ]
