# Generated by Django 4.1.5 on 2023-01-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_goal_deadline_remove_goal_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.IntegerField(choices=[(0, 'doing'), (1, 'Done'), (2, 'Wasted')], default='doing'),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.IntegerField(choices=[(0, 'doing'), (1, 'Done'), (2, 'Wasted')], default='doing'),
        ),
    ]
